#ifndef _KEYMAP_H_
#define _KEYMAP_H_

#include "common.h"

NAMESPACE_BEGIN

//game actions
enum Actions
{
  ACTION_MOVE_FORW = 0,
  ACTION_MOVE_BACK,
  ACTION_MOVE_LEFT,
  ACTION_MOVE_RIGHT,
  ACTION_MOVE_UP,
  ACTION_MOVE_DOWN,
  ACTION_Y_RESET,
  ACTION_LOOK_UP,
  ACTION_LOOK_DOWN,
  ACTION_TURN_LEFT,
  ACTION_TURN_RIGHT,
  ACTION_ZOOM_IN,
  ACTION_ZOOM_OUT,
  ACTION_ZOOM_RESET,
  ACTION_JUMP,
  ACTION_FLASH_LIGHT,
  ACTION_FIRE_1,
  ACTION_FIRE_2,
  ACTION_WEAPON_NEXT,
  ACTION_WEAPON_PREV,
  ACTION_WEAPON_1,
  ACTION_WEAPON_2,
  ACTION_WEAPON_3,
  ACTION_WEAPON_4,
  ACTION_WEAPON_5,
  ACTION_WEAPON_6,
  ACTION_WEAPON_7,
  ACTION_WEAPON_8,
  ACTION_WEAPON_9,
  ACTION_MENU,
  ACTION_MENU_UP,
  ACTION_MENU_DOWN,
  ACTION_MENU_LEFT,
  ACTION_MENU_RIGHT,
  ACTION_MENU_SELECT,
  ACTION_FIRST  = ACTION_MOVE_FORW,
  ACTION_LAST   = ACTION_MENU_SELECT,
  NUM_ACTIONS   = ACTION_LAST + 1,
};

//virtual keys
enum Keys
{
  NUM_KEYS_ASCII    = 128,
  NUM_KEYS_SYS      = 4,
  NUM_KEYS_MOUSE    = 5,
  NUM_KEYS          = NUM_KEYS_ASCII +
                      NUM_KEYS_SYS   +
                      NUM_KEYS_MOUSE,

  BASE_KEYS_ASCII   = 0,
  BASE_KEYS_SYS     = BASE_KEYS_ASCII + NUM_KEYS_ASCII,
  BASE_KEYS_MOUSE   = BASE_KEYS_SYS   + NUM_KEYS_SYS,

  KEY_SPACE         = 8,
  KEY_ENTER         = 13,
  KEY_ESCAPE        = 27,

  SYS_KEY_LEFT        = BASE_KEYS_SYS,
  SYS_KEY_UP          = BASE_KEYS_SYS + 1,
  SYS_KEY_RIGHT       = BASE_KEYS_SYS + 2,
  SYS_KEY_DOWN        = BASE_KEYS_SYS + 3,

  MOUSE_BUTTON_LEFT     = BASE_KEYS_MOUSE,
  MOUSE_BUTTON_MIDDLE   = BASE_KEYS_MOUSE + 1,
  MOUSE_BUTTON_RIGHT    = BASE_KEYS_MOUSE + 2,
  MOUSE_WHEEL_DOWN      = BASE_KEYS_MOUSE + 3,
  MOUSE_WHEEL_UP        = BASE_KEYS_MOUSE + 4,
};

NAMESPACE_END

#endif //_KEYMAP_H_
