OBJ		=	$(SRC:.cpp=.o)
TARGET		:=	$(BIN_DIR)/$(TARGET)

.PHONY: all
all: $(TARGET)

.PHONY: test
test: $(TEST)

$(TARGET): $(OBJ) $(SRC) $(BIN_DIR)
	$(CXX) $(LDFLAGS) $(OBJ) -o $@

$(BIN_DIR):
	mkdir $(BIN_DIR)

.PHONY: clean
clean: clean_bin

.PHONY: clean_bin
clean_bin:
	rm -f $(OBJ) $(TARGET)

%.o: %.cpp %.h $(DEPS)
	$(CXX) $(CXXFLAGS) -c $< -o $@

%.o: %.cpp $(DEPS)
	$(CXX) $(CXXFLAGS) -c $< -o $@
